export const GRADING = [
    {
      "English": "FAULTY PSU/ADAPTOR",
      "German": "PSU/ADAPTOR DEFEKT",
      "French": "ALIMENTATION HS",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "BATTERY-FAULTY",
      "German": "BATTERY DEFEKT",
      "French": "BATTERIE HS",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "MISSING BATTERY",
      "German": "AKKU FEHLT",
      "French": "BATTERIE MANQUANTE",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "BEZEL BROKEN",
      "German": "BEZEL ZERBROCHEN",
      "French": "BEZEL CASSE",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "SCRATCHES ON BEZEL",
      "German": "KRATZER AUF DER BEZEL",
      "French": "BEZEL RAYE",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["3","4"],
      "Comment":""
    },
    {
      "English": "LOCKED GOOGLE",
      "German": "GOOGLE BLOKE",
      "French": "BLOQUE GOOGLE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "LOCKED ICLOUD ID",
      "German": "GESPERRTE ICLOUD-ID",
      "French": "BLOQUE ICLOUD",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "LOCKED MDM",
      "German": "GESPERRT MDM",
      "French": "BLOQUE MDM",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "",
      "German": "",
      "French": "BOITIER ABIME",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["3"],
      "Comment":""
    },
    {
      "English": "BROKEN CASE",
      "German": "GEHÄUSESCHADEN",
      "French": "BOITIER CASSE",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "STICKY CASE",
      "German": "STICKY CASE",
      "French": "BOITIER COLLANT (TACHE DE COLLE)",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "HEAVILY SCUFFED CASE",
      "German": "STARK ABGENUTZT",
      "French": "BOITIER FORTEMENT ABIME",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "HEAVILY SCRATCHED CASE",
      "German": "STARKE KRATZER",
      "French": "BOITIER FORTEMENT RAYE",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "SCRATCHED CASE",
      "German": "GESTRAHLTES GEHÄUSE",
      "French": "BOITIER RAYE",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["3"],
      "Comment":""
    },
    {
      "English": "TWISTED CASE",
      "German": "VERDREHTES GEHÄUSE",
      "French": "BOITIER TORDU",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "PAPER JAM",
      "German": "PAPIERSTAU",
      "French": "BOURRAGE PAPIER",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "FAULTY MENU BUTTON",
      "German": "MENUTASTSE DEFEKT",
      "French": "BOUTON MENU HS",
      "LT": false,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY ON/OFF SWITCH",
      "German": "AN/AUS TASTE DEFEKT",
      "French": "BOUTON POWER HS",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F","S6"],
      "Comment":""
    },
    {
      "English": "FAULTY BACK CAMERA",
      "German": "RÜCKFAHRKAMERA HS",
      "French": "CAMERA ARRIERE HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY MOTHERBOARD",
      "German": "MOTHERBOARD DEFEKT",
      "French": "CARTE MERE HS",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "MISSING CD/DVD",
      "German": "CD/DVD FEHLT",
      "French": "CD/DVD MANQUANT",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "FAULTY HINGE BETWEEN SCREEN AND MOTHERBOARD",
      "German": "DEFEKTES SCHARNIER",
      "French": "CHARNIERES HS",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY KEYBOARD",
      "German": "TASTATUR DEFEKT",
      "French": "CLAVIER HS",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "MISSING KEYBOARD",
      "German": "FEHLENDE TASTATUR",
      "French": "CLAVIER MANQUANT",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "USED KEYBOARD",
      "German": "BENUTZTES KEYBOARD",
      "French": "CLAVIER USE",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "COMPUTRACE",
      "German": "COMPUTRACE",
      "French": "COMPUTRACE",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "RAID CONTROLLER NOT WORKING",
      "German": "RAID-CONTROLLER FUNKTIONIERT NICHT",
      "French": "CONTROLEUR RAID HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "CRACKED SCREEN",
      "German": "DISPLAY GEBROCHEN",
      "French": "DALLE BRISEE",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "HEAVILY DAR",
      "German": "STARK DAR",
      "French": "DAR FORT",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["IMAGE BRULE"],
      "Comment":""
    },
    {
      "English": "FAULTY LCD DISPLAY",
      "German": "LCD DISPLAY DEFEKT",
      "French": "DEFAUT LCD",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "DISPLAY PORT NOT WORKING",
      "German": "DISPLAY PORT FUNKTIONIERT NICHT",
      "French": "DISPLAY PORT HS",
      "LT": false,
      "PC": true,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "TRANSPORT DAMAGE",
      "German": "TRANSPORTSCHADEN",
      "French": "DOMMAGE DU AU TRANSPORT",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "SMASHED SCREEN",
      "German": "BILDSCHIRM GEBROCHEN",
      "French": "ECRAN CASSE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "HEAVILY SCRATCHED SCREEN",
      "German": "STARK ZERKRATZTER BILDSCHIRM",
      "French": "ECRAN FORTEMENT RAYE",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["A","4"],
      "Comment":""
    },
    {
      "English": "SCRATCHED SCREEN",
      "German": "BILDSCHIRM KRATZER",
      "French": "ECRAN RAYE",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["A","3"],
      "Comment":""
    },
    {
      "English": "PRESS MARKS ON SCREEN.",
      "German": "DRUCKSTELLEN AM DISPLAY",
      "French": "ECRAN TACHE",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["A","4"],
      "Comment":""
    },
    {
      "English": "BELOW MINIMUM CONFIGURATION",
      "German": "UNTER MINIMUM CONFIGURATION",
      "French": "EN DESSOUS DE LA CONFIGURATION MINIMUM",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": false,
      "LP": true,
      "SP": true,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "TONER/INK LEAKAGE",
      "German": "TONER AUSGELAUFEN",
      "French": "FUITE TONER ENCRE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "SPEAKERS FAULTY",
      "German": "HS-LAUTSPRECHER",
      "French": "HAUT PARLEURS HS",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "SMALLER THAN 17 INCHES",
      "German": "KLEINER ALS 17 ZOLL",
      "French": "INFERIEUR A 17 POUCES",
      "LT": false,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "CRACKED LCD",
      "German": "RISS AM LCD",
      "French": "LCD HS",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "PERMANENT LOGO",
      "German": "PERMANENT LOGO-AUFKLEBER",
      "French": "LOGO PERMANENT",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "ETCHED LOGO/ASSET TO CASE TO CASE",
      "German": "PERMANENT LOGO-AUFKLEBER",
      "French": "LOGO-TAG ANTIVOL",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "MISSING POWER ADAPTER",
      "German": "NETZTEIL FEHLT",
      "French": "MANQUE ALIMENTATION",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "MISSING SHEET FEEDERS",
      "German": "PAPIEREINZUG FEHLT",
      "French": "MANQUE BAC FEUILLE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "MISSING PSU/ADAPTOR",
      "German": "PSU/ADAPTOR FEHLT",
      "French": "MANQUE BLOC ALIMENTATION",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "MISSING COVER PANELS",
      "German": "BLENDE FEHLT",
      "French": "MANQUE COUVERCLE - CACHE",
      "LT": false,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["L"],
      "Comment":""
    },
    {
      "English": "MISSING DUPLEXER",
      "German": "DUPLEXEINHEIT FEHLT",
      "French": "MANQUE DUPLEXEUR",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "MISSING FRONT PANEL COVER",
      "German": "ABDECKUNG FEHLT",
      "French": "MANQUE FACADE",
      "LT": false,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["L"],
      "Comment":""
    },
    {
      "English": "MISSING HDD",
      "German": "HDD FEHLT",
      "French": "MANQUE HDD",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "MISSING MEMORY",
      "German": "RAM FEHLT",
      "French": "MANQUE MEMOIRE",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "MISSING SCREEN STAND",
      "German": "FUSS FEHLT",
      "French": "MANQUE PIED",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "MISSING PROCESSOR",
      "German": "PROZESSOR FEHLT",
      "French": "MANQUE PROCESSEUR",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "RAILS MISSING",
      "German": "SCHIENEN FEHLEN",
      "French": "MANQUE RAIL",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["-"],
      "Comment":"RACKMOUNT DAMAGED Y/N/ N/A CHOISIR N/A"
    },
    {
      "English": "MISSING PEN",
      "German": "FEHLENDER KUGELSCHREIBER",
      "French": "MANQUE STYLET",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "MISSING HDD CADDY",
      "German": "HDD RAHMEN FEHLT",
      "French": "MANQUE SUPPORT HDD",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["L"],
      "Comment":""
    },
    {
      "English": "MISSING PAPER TRAY",
      "German": "PAPIERFACH FEHLT",
      "French": "MANQUE TIROIR",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "MISSING TONER",
      "German": "TONER FEHLT",
      "French": "MANQUE TONER",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "MISSING FUSER UNIT",
      "German": "FUSER FEHLT",
      "French": "MANQUE UNITE DE FUSION",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "MISSING SCREWS",
      "German": "FEHLENDE SCHRAUBEN",
      "French": "MANQUE VIS",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["L"],
      "Comment":""
    },
    {
      "English": "BAD-PRINTOUT-QUALITY",
      "German": "SCHLECHTER AUSDRUCK",
      "French": "MAUVAISE QUALITE D'IMPRESSION",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "FAULTY MICROPHONE",
      "German": "MIKROPHONE HS",
      "French": "MICRO HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "NO POWER ON",
      "German": "EINSCHALT FEHLER",
      "French": "NE S'ALLUME PAS",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "NON TESTED",
      "German": "NICHT TESTEN",
      "French": "NON TESTE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "NON-D",
      "German": "NON-D",
      "French": "NON-D",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["-"],
      "Comment":""
    },
    {
      "English": "OXYDATION",
      "German": "OXYDATION",
      "French": "OXYDATION",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["4","S6"],
      "Comment":""
    },
    {
      "English": "NO LICENCE",
      "German": "KEINE LIZENZ",
      "French": "PAS DE LICENCE",
      "LT": false,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["-"],
      "Comment":"NO DANS LE DYNAMIC"
    },
    {
      "English": "NO VIDEO SIGNAL",
      "German": "KEIN BILD",
      "French": "PAS DE SIGNAL VIDEO",
      "LT": false,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "BIOS PASSWORD PROTECTED",
      "German": "BIOS PASSWORT GESCHÜTZT",
      "French": "PASSWORD BIOS",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["-"],
      "Comment":"RENVOYER BEAUCOUP DE MESSAGE A L'ADV"
    },
    {
      "English": "BIOS PASSWORD REMOVED",
      "German": "BIOS PASSWORT ENTFERNT",
      "French": "PASSWORD BIOS ENLEVE",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["-"],
      "Comment":""
    },
    {
      "English": "FAULTY SCREEN STAND",
      "German": "DEFEKTER BILDSCHIRMSTÄNDER",
      "French": "PIED HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "CMOS-BATTERY-EMPTY",
      "German": "CMOS-BATTERY-LEER",
      "French": "PILE CMOS VIDE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["-"],
      "Comment":""
    },
    {
      "English": "WHITE SPOT",
      "German": "",
      "French": "POINT BLANC",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "CHARGING PORT FAULTY",
      "German": "LADEANSCHLUSS DEFEKT",
      "French": "PORT DE CHARGE DEFECTUEUX",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "FAULTY DVI",
      "German": "DVI FUNKTIONIERT NICHT",
      "French": "PORT DVI HS",
      "LT": false,
      "PC": true,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "NETWORK NOT WORKING",
      "German": "NETZWERKANSCHLUSS FEHLT",
      "French": "PORT ETHERNET HS",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F","F4"],
      "Comment":"F SI RJ45 HS et F+4 SI PORT RJ45 CASSE"
    },
    {
      "English": "HDMI NOT WORKING",
      "German": "HDMI FUNKTIONIERT NICHT",
      "French": "PORT HDMI HS",
      "LT": false,
      "PC": true,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY SIM PORT",
      "German": "SIM AUSSERHALB",
      "French": "PORT SIM HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F","S6"],
      "Comment":""
    },
    {
      "English": "USB PORT FAULTY",
      "German": "USB-ANSCHLUSS DEFEKT",
      "French": "PORT USB HS",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY VGA",
      "German": "VGA FUNKTIONIERT NICHT",
      "French": "PORT VGA HS",
      "LT": false,
      "PC": true,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "MISSING SIM GATE",
      "German": "SIM-KARTENSLOT FEHLT",
      "French": "PORTE SIM MANQUANT",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "FACTORY RESET PERFORMED",
      "German": "AUF WERKSEINSTELLUNGEN ZURÜCKGESETZT",
      "French": "RETOUR AUX PARAMETRES USINE EFFECTUE",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["A","F"],
      "Comment":""
    },
    {
      "English": "SERVICE ERROR",
      "German": "SERVICE-FEHLER",
      "French": "SERVICE ERROR",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "GLUE STAIN",
      "German": "",
      "French": "TACHE DE COLLE",
      "LT": true,
      "PC": true,
      "FS": true,
      "OT": true,
      "LP": true,
      "SP": true,
      "SV": true,
      "GRADE": ["4"],
      "Comment":"Peut être également en 3 si leger, sans le notifier dans l'entered comment"
    },
    {
      "English": "TACTILE",
      "German": "TACTILE",
      "French": "TACTILE",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["-"],
      "Comment":"AUCUN GRADE"
    },
    {
      "English": "FAULTY TOUCHSCREEN",
      "German": "TOUCHSCREEN DEFEKT",
      "French": "TACTILE HS",
      "LT": true,
      "PC": false,
      "FS": true,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY ROLLERS",
      "German": "ROLLEN DEFEKT",
      "French": "TAMBOURS DEFECTUEUX",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "TEST PRINT FAILED",
      "German": "TESTDRUCK FEHLGESCHLAGEN",
      "French": "TEST IMPRESSION ECHOUE",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "TONER BELOW 25%",
      "German": "TONER UNTER 25%",
      "French": "TONER INFERIEUR A 25%",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "KEYS DELETED",
      "German": "SCHLÜSSEL GELÖSCHT",
      "French": "TOUCHES EFFACEES (CLAVIER USE)",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "MISSING KEYS",
      "German": "FEHLENDE SCHLÜSSEL",
      "French": "TOUCHES MANQUANTES",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F", "L"],
      "Comment":""
    },
    {
      "English": "FAULTY TOUCHPAD",
      "German": "TOUCHPAD DEFEKT",
      "French": "TOUCHPAD HS",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "USED TOUCHPAD",
      "German": "BENUTZTES TOUCHPAD",
      "French": "TOUCHPAD USE",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["4"],
      "Comment":""
    },
    {
      "English": "FAULTY TOUCH ID",
      "German": "TOUCH ID AUSSERHALB",
      "French": "TOUH ID HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": true,
      "LP": false,
      "SP": true,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY TRANSFER BELT",
      "German": "TRANSFER BELT OFF",
      "French": "TRANSFERT BELT HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": true,
      "SP": false,
      "SV": false,
      "GRADE": ["S6"],
      "Comment":""
    },
    {
      "English": "FAULTY FAN",
      "German": "FAN FUNKTIONIERT NICHT",
      "French": "VENTILATEUR HS",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F","S6"],
      "Comment":""
    },
    {
      "English": "VIBRATION FAULTY",
      "German": "VIBRATION DEFEKT",
      "French": "VIBREUR HS",
      "LT": false,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": true,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "FAULTY WEBCAM",
      "German": "WEBCAM FUNKTIONIERT NICHT",
      "French": "WEBCAM HS",
      "LT": true,
      "PC": false,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": false,
      "SV": false,
      "GRADE": ["F"],
      "Comment":""
    },
    {
      "English": "",
      "German": "",
      "French": "DISQUE DUR HS ENLEVER, DEGAUSSE ET DETRUIT",
      "LT": true,
      "PC": true,
      "FS": false,
      "OT": false,
      "LP": false,
      "SP": true,
      "SV": true,
      "GRADE": ["F", "L"],
      "Comment":"SAUF QUAND 1 DISQUE SUR 2 FAIL NE PAS MODIFIER LE GRADE"
    }
  ]